FROM tomcat:9-jdk14-openjdk-oracle
LABEL maintainer="disantoroberto@gmail.com"
LABEL name="bang"
# http://localhost:8080/westerncardgame/
EXPOSE 8080
COPY westerncardgame.war /usr/local/tomcat/webapps/
